title:            tdoly's blog
tagline:          学而知吾不足
description:      This blog will write down my work and life in dribs and drabs
#Comment out url when working locally to resolve base urls correctly
url:              http://blog.tdoly.com
#url:              http://localhost:4000

#blog图片存放在七牛
head_image_url:   http://blog-tdoly-com.u.qiniudn.com/@/image/blog/head/
body_image_url:   http://blog-tdoly-com.u.qiniudn.com/@/image/blog/body/

# Owner/author information
owner:
  name:           tdoly
  avatar:         bio-photo.jpg
  bio:            "喜爱爬山，徒步的IT小小鸟"
  email:          tdolydong@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        tdolydong
  facebook:       tdolydong
  github:         tdoly
  linkedin:
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/100632295595947080848/posts
  #weibo
  weibo: tdoly

#weibo
weibo_uid: 2038720681
weibo_verifier: 95bc61d7
weibo_fansline: 0 # 粉丝显示多少行
weibo_show: true # 是否显示最近微博内容
weibo_pic: true # 是否显示微博中的图片
weibo_skin: 10 # 使用哪种配色风格，数字为从1开始的微博秀风格序号

# Analytics and webmaster tools stuff goes here
google_analytics: UA-45893829-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
disqus:
  short_name: tdolydong

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles
    external: false
  - title: Demo
    url: http://demo.tdoly.com

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
